import { Injectable } from '@angular/core';

import { InMemoryDbService } from 'angular-in-memory-web-api';
@Injectable({
  providedIn: 'root'
})
export class MemoryServiceService implements InMemoryDbService {

  constructor() { }

  createDb() {
    const applied = {
      "status": {
        "code": 200,
        "message": "success"
      },
      "leave_associate_list": [
        {
          "employee_id": "008088",
          "employee_name": "Daw   Zin Zin Naing",
          "designation": "Front-end Designer Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-02-13T00:00:00+06:30",
          "leave_end_date": "2020-02-13T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008136",
          "employee_name": "Daw   Moe Moe Myint",
          "designation": "Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-02-19T00:00:00+06:30",
          "leave_end_date": "2020-02-19T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008136",
          "employee_name": "Daw   Moe Moe Myint",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-20T00:00:00+06:30",
          "leave_end_date": "2020-03-20T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008136",
          "employee_name": "Daw   Moe Moe Myint",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-21T00:00:00+06:30",
          "leave_end_date": "2020-03-23T00:00:00+06:30",
          "half_type": "",
          "duration": "2.0",
          "remark": "NNA Testing",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008136",
          "employee_name": "Daw   Moe Moe Myint",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-03-25T00:00:00+06:30",
          "leave_end_date": "2020-03-25T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-27T00:00:00+06:30",
          "leave_end_date": "2020-03-27T00:00:00+06:30",
          "half_type": "9",
          "duration": "0.0",
          "remark": "Personeal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-28T00:00:00+06:30",
          "leave_end_date": "2020-03-28T00:00:00+06:30",
          "half_type": "9",
          "duration": "0.0",
          "remark": "Personeal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-03-30T00:00:00+06:30",
          "leave_end_date": "2020-03-30T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008136",
          "employee_name": "Daw   Moe Moe Myint",
          "designation": "Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-03-31T00:00:00+06:30",
          "leave_end_date": "2020-03-31T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008088",
          "employee_name": "Daw   Zin Zin Naing",
          "designation": "Front-end Designer Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-04-01T00:00:00+06:30",
          "leave_end_date": "2020-04-01T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-06-12T00:00:00+06:30",
          "leave_end_date": "2020-06-12T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-06-13T00:00:00+06:30",
          "leave_end_date": "2020-06-13T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-06-15T00:00:00+06:30",
          "leave_end_date": "2020-06-15T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-06-16T00:00:00+06:30",
          "leave_end_date": "2020-06-16T00:00:00+06:30",
          "half_type": "2",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-06-18T00:00:00+06:30",
          "leave_end_date": "2020-06-18T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "com.google.android.material.textfield.TextInputEditText{417f887 VFED..CL. ........ 0,0-948,275 #7f0a0106 app:id/reason_comment}",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-06-24T00:00:00+06:30",
          "leave_end_date": "2020-06-24T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008257",
          "employee_name": "U     Aung Kyaw Phyo",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-06-27T00:00:00+06:30",
          "leave_end_date": "2020-06-27T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "Blah blah",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008257",
          "employee_name": "U     Aung Kyaw Phyo",
          "designation": "Developer",
          "leave_type_code": "CPL",
          "leave_start_date": "2020-06-28T00:00:00+06:30",
          "leave_end_date": "2020-06-28T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-06-29T00:00:00+06:30",
          "leave_end_date": "2020-06-29T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "com.google.android.material.textfield.TextInputEditText{417f887 VFED..CL. ........ 0,0-948,275 #7f0a0106 app:id/reason_comment}",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008257",
          "employee_name": "U     Aung Kyaw Phyo",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-07-01T00:00:00+06:30",
          "leave_end_date": "2020-07-01T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "OD",
          "leave_start_date": "2020-07-04T00:00:00+06:30",
          "leave_end_date": "2020-07-04T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "OD",
          "leave_start_date": "2020-07-05T00:00:00+06:30",
          "leave_end_date": "2020-07-05T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "007326",
          "employee_name": "U     Myat Thu",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-06T00:00:00+06:30",
          "leave_end_date": "2020-07-06T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "OD",
          "leave_start_date": "2020-07-06T00:00:00+06:30",
          "leave_end_date": "2020-07-06T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "006216",
          "employee_name": "U     Ye Htut Hlaing",
          "designation": "Senior Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-07T00:00:00+06:30",
          "leave_end_date": "2020-07-07T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "007326",
          "employee_name": "U     Myat Thu",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-07T00:00:00+06:30",
          "leave_end_date": "2020-07-07T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Annual leave testing.",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "OD",
          "leave_start_date": "2020-07-07T00:00:00+06:30",
          "leave_end_date": "2020-07-07T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "007326",
          "employee_name": "U     Myat Thu",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-08T00:00:00+06:30",
          "leave_end_date": "2020-07-08T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Get leave from 8 annual leave.",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "007326",
          "employee_name": "U     Myat Thu",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-09T00:00:00+06:30",
          "leave_end_date": "2020-07-09T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "007358",
          "employee_name": "U     Wai Phyo Han",
          "designation": "Full Stack Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-20T00:00:00+06:30",
          "leave_end_date": "2020-07-20T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "007358",
          "employee_name": "U     Wai Phyo Han",
          "designation": "Full Stack Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-23T00:00:00+06:30",
          "leave_end_date": "2020-07-23T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "MTL",
          "leave_start_date": "2020-08-08T00:00:00+06:30",
          "leave_end_date": "2020-08-09T00:00:00+06:30",
          "half_type": "",
          "duration": "2.0",
          "remark": "",
          "status": "1",
          "status_description": "Applied"
        }
      ]
    }

    const approved = {
      "status": {
        "code": 200,
        "message": "success"
      },
      "leave_associate_list": [
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-03-10T00:00:00+06:30",
          "leave_end_date": "2020-03-10T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007359",
          "employee_name": "U     Hsu Naing",
          "designation": "Full Stack Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-03-12T00:00:00+06:30",
          "leave_end_date": "2020-03-12T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008136",
          "employee_name": "Daw   Moe Moe Myint",
          "designation": "Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-03-12T00:00:00+06:30",
          "leave_end_date": "2020-03-13T00:00:00+06:30",
          "half_type": "",
          "duration": "2.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008136",
          "employee_name": "Daw   Moe Moe Myint",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-17T00:00:00+06:30",
          "leave_end_date": "2020-03-17T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "NNA Testing",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008088",
          "employee_name": "Daw   Zin Zin Naing",
          "designation": "Front-end Designer Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-18T00:00:00+06:30",
          "leave_end_date": "2020-03-18T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "SL",
          "leave_start_date": "2020-03-19T00:00:00+06:30",
          "leave_end_date": "2020-03-19T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008136",
          "employee_name": "Daw   Moe Moe Myint",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-03-19T00:00:00+06:30",
          "leave_end_date": "2020-03-19T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007359",
          "employee_name": "U     Hsu Naing",
          "designation": "Full Stack Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-20T00:00:00+06:30",
          "leave_end_date": "2020-03-20T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008088",
          "employee_name": "Daw   Zin Zin Naing",
          "designation": "Front-end Designer Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-20T00:00:00+06:30",
          "leave_end_date": "2020-03-20T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "SL",
          "leave_start_date": "2020-03-20T00:00:00+06:30",
          "leave_end_date": "2020-03-20T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007432",
          "employee_name": "U     Kyaw Zin Tun",
          "designation": "Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-03-20T00:00:00+06:30",
          "leave_end_date": "2020-03-20T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "006216",
          "employee_name": "U     Ye Htut Hlaing",
          "designation": "Senior Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-03-20T00:00:00+06:30",
          "leave_end_date": "2020-03-20T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "race",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-21T00:00:00+06:30",
          "leave_end_date": "2020-03-22T00:00:00+06:30",
          "half_type": "",
          "duration": "2.0",
          "remark": "NNA Testing",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-03-24T00:00:00+06:30",
          "leave_end_date": "2020-03-24T00:00:00+06:30",
          "half_type": "2",
          "duration": "0.0",
          "remark": "NNA Testing",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-03-25T00:00:00+06:30",
          "leave_end_date": "2020-03-25T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-26T00:00:00+06:30",
          "leave_end_date": "2020-03-26T00:00:00+06:30",
          "half_type": "9",
          "duration": "1.0",
          "remark": "Personeal Case",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-04-01T00:00:00+06:30",
          "leave_end_date": "2020-04-04T00:00:00+06:30",
          "half_type": "",
          "duration": "4.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-06-14T00:00:00+06:30",
          "leave_end_date": "2020-06-14T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "Personal Case",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-07-01T00:00:00+06:30",
          "leave_end_date": "2020-07-01T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-02T00:00:00+06:30",
          "leave_end_date": "2020-07-02T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007359",
          "employee_name": "U     Hsu Naing",
          "designation": "Full Stack Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-02T00:00:00+06:30",
          "leave_end_date": "2020-07-02T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "OD",
          "leave_start_date": "2020-07-03T00:00:00+06:30",
          "leave_end_date": "2020-07-03T00:00:00+06:30",
          "half_type": "2",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-04T00:00:00+06:30",
          "leave_end_date": "2020-07-08T00:00:00+06:30",
          "half_type": "",
          "duration": "5.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007358",
          "employee_name": "U     Wai Phyo Han",
          "designation": "Full Stack Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-07-08T00:00:00+06:30",
          "leave_end_date": "2020-07-10T00:00:00+06:30",
          "half_type": "",
          "duration": "3.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-07-10T00:00:00+06:30",
          "leave_end_date": "2020-07-12T00:00:00+06:30",
          "half_type": "",
          "duration": "3.0",
          "remark": "Personal Case",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-15T00:00:00+06:30",
          "leave_end_date": "2020-07-15T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-17T00:00:00+06:30",
          "leave_end_date": "2020-07-17T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008257",
          "employee_name": "U     Aung Kyaw Phyo",
          "designation": "Developer",
          "leave_type_code": "CL",
          "leave_start_date": "2020-07-24T00:00:00+06:30",
          "leave_end_date": "2020-07-24T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008257",
          "employee_name": "U     Aung Kyaw Phyo",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-25T00:00:00+06:30",
          "leave_end_date": "2020-07-25T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-29T00:00:00+06:30",
          "leave_end_date": "2020-07-29T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "com.google.android.material.textfield.TextInputEditText{fbdd39f VFED..CL. ........ 0,0-948,275 #7f0a0106 app:id/reason_comment}",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-07-30T00:00:00+06:30",
          "leave_end_date": "2020-07-30T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        },
        {
          "employee_id": "007992",
          "employee_name": "Daw   Naw Say Say Shee",
          "designation": "Full Stack Developer",
          "leave_type_code": "WPL",
          "leave_start_date": "2020-08-04T00:00:00+06:30",
          "leave_end_date": "2020-08-04T00:00:00+06:30",
          "half_type": "2",
          "duration": "1.0",
          "remark": "",
          "status": "2",
          "status_description": "Approved"
        }
      ]
    }

    const rejected = {
      "status": {
        "code": 200,
        "message": "success"
      },
      "leave_associate_list": [
        {
          "employee_id": "008164",
          "employee_name": "Daw   Nwe Ni Aung",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-03-16T00:00:00+06:30",
          "leave_end_date": "2020-03-16T00:00:00+06:30",
          "half_type": "",
          "duration": "1.0",
          "remark": "NNA Testing",
          "status": "3",
          "status_description": "Rejected"
        },
        {
          "employee_id": "008257",
          "employee_name": "U     Aung Kyaw Phyo",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-06-25T00:00:00+06:30",
          "leave_end_date": "2020-06-26T00:00:00+06:30",
          "half_type": "",
          "duration": "2.0",
          "remark": "Sick blah blah",
          "status": "3",
          "status_description": "Rejected"
        },
        {
          "employee_id": "008257",
          "employee_name": "U     Aung Kyaw Phyo",
          "designation": "Developer",
          "leave_type_code": "AL",
          "leave_start_date": "2020-06-29T00:00:00+06:30",
          "leave_end_date": "2020-06-29T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "3",
          "status_description": "Rejected"
        },
        {
          "employee_id": "008257",
          "employee_name": "U     Aung Kyaw Phyo",
          "designation": "Developer",
          "leave_type_code": "OD",
          "leave_start_date": "2020-06-30T00:00:00+06:30",
          "leave_end_date": "2020-06-30T00:00:00+06:30",
          "half_type": "1",
          "duration": "1.0",
          "remark": "",
          "status": "3",
          "status_description": "Rejected"
        }
      ]
    }


    const success = {
      "status": {
        "code": 200,
        "message": "success"
      },
      "data": {
        "approve_leave_record_result": "0"
      }
    }
    return { applied, approved, rejected, success } // add as many end-points you want
  }
}
